<li class="dropdown">
          <meta charset="UTF-8">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <span class="glyphicon glyphicon-shopping-cart"></span>Ostoskori<span class="caret"></span></a>
          <ul class="dropdown-menu dropdown-cart" role="menu">
            
                            
              
              
              
              <li>
                  <span class="item">
                    <span class="item-left">
                        
                        <span class="item-info">
                            <span>TYHJÄ</span>
                            
                        </span>
                    </span>
                    <!--<span class="item-right">
                        <button class="btn btn-xs btn-danger pull-right">x</button>
                    </span>-->
                </span>
              </li>
              <li class="divider"></li>
              <li><a class="text-center" href="Tilaus">Tee tilaus</a></li>